// MC Training — Service Worker v2
// Relative-path precache so the app works at any GitHub Pages project subpath

const CACHE_NAME = 'mc-training-v134';
const BASE = 'https://mcross2298.github.io/4-Weeks-to-Open-/';
// The list below is generated by tools/build-sw.py — do not edit by hand.
const CACHE_URLS = [
    /* AUTOGEN:URLS START */
    './',
    './apple-touch-icon.png',
    './base.css',
    './conditioning-data.js',
    './conditioning-elite.css',
    './dashboard.html',
    './exercise-catalog.js',
    './gainz-dark.css',
    './icon-192-maskable.png',
    './icon-192.png',
    './icon-512-maskable.png',
    './icon-512.png',
    './icon.svg',
    './index.html',
    './manifest.json',
    './mc-account.js',
    './mc-appearance.js',
    './mc-backup-status.js',
    './mc-barcode.js',
    './mc-biomech.js',
    './mc-biometric.js',
    './mc-body.js',
    './mc-bonus-routing.js',
    './mc-calendar.js',
    './mc-card-actions.css',
    './mc-card-actions.js',
    './mc-chart.js',
    './mc-collections.js',
    './mc-cond-suggest.js',
    './mc-cond.js',
    './mc-cues-data.js',
    './mc-cues.js',
    './mc-data.js',
    './mc-engine.js',
    './mc-exercise-catalog.js',
    './mc-exercise-trends.js',
    './mc-export.js',
    './mc-finish.js',
    './mc-foodapi.js',
    './mc-global-search.js',
    './mc-group-split.js',
    './mc-guided.js',
    './mc-install.js',
    './mc-interval.js',
    './mc-layout.js',
    './mc-light.css',
    './mc-live-tracker.js',
    './mc-macrocalc.js',
    './mc-macros.js',
    './mc-maxout.js',
    './mc-muscle-map.js',
    './mc-naming-paint.js',
    './mc-naming.js',
    './mc-nav.css',
    './mc-nav.js',
    './mc-onboarding.js',
    './mc-pm-creator.js',
    './mc-pm-data.js',
    './mc-pm-inline.js',
    './mc-pm-layout-editor.js',
    './mc-program-builder.js',
    './mc-program-hero.css',
    './mc-program-hero.js',
    './mc-program-landing.css',
    './mc-program-pub.js',
    './mc-program-status.js',
    './mc-program-store.js',
    './mc-push.js',
    './mc-quick-pump.js',
    './mc-recap.js',
    './mc-rep-progress.js',
    './mc-replace.js',
    './mc-reps.js',
    './mc-resume.js',
    './mc-schedule.js',
    './mc-session.js',
    './mc-setlog.css',
    './mc-setlog.js',
    './mc-share.js',
    './mc-stats.js',
    './mc-suggest.js',
    './mc-summary.css',
    './mc-summary.js',
    './mc-supabase.js',
    './mc-superset-hop.js',
    './mc-surprise.css',
    './mc-surprise.js',
    './mc-sw-update.js',
    './mc-swap-manager.js',
    './mc-sync.js',
    './mc-theme.js',
    './mc-timer.js',
    './mc-voice.js',
    './mc-wrapped.js',
    './mcdb.js',
    './mm-data.js',
    './mm-engine.js',
    './onyx-conditioning-tokens-and-styles.css',
    './onyx-programs-tokens-and-styles.css',
    './onyx-tokens-and-styles.css',
    './pmc-data.js',
    './pmc-s7-data.js',
    './program-manager.js',
    './program-overrides.js',
    './program-overrides.json',
    './stndr-checkoff.js',
    './superset-timers.js',
    './sw.js'
    /* AUTOGEN:URLS END */
];

// Install — cache everything
self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            console.log('[SW] Caching', CACHE_URLS.length, 'files');
            // Cache in batches to avoid timeout
            const batch = (arr, size) => Array.from({length:Math.ceil(arr.length/size)}, (_,i) => arr.slice(i*size,i*size+size));
            const batches = batch(CACHE_URLS, 20);
            return batches.reduce((p, b) => p.then(() =>
                Promise.allSettled(b.map(u => cache.add(u).catch(err => console.log('[SW] Cache miss:', u, err))))
            ), Promise.resolve());
        })
    );
    // NOTE: intentionally NOT calling self.skipWaiting() here. Activation is
    // page-controlled (mc-sw-update.js posts 'skipWaiting' only when no workout
    // is in progress) so a new build never force-reloads someone mid-set.
});

// Activate — remove ALL old caches and take control. The page-side reload is
// driven by mc-sw-update.js's 'controllerchange' handler (which guards against
// reloading mid-workout), so we do NOT force-navigate tabs here.
self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys()
            .then(keys => Promise.all(
                keys.filter(k => k !== CACHE_NAME).map(k => {
                    console.log('[SW] Removing old cache:', k);
                    return caches.delete(k);
                })
            ))
            .then(() => self.clients.claim())
    );
});

// Offline fallback page (shared by the HTML + asset handlers).
function offlinePage(msg) {
    return new Response(
        '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">' +
        (msg || 'You are offline.') +
        '</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
        { headers: { 'Content-Type': 'text/html' } }
    );
}

// HTML strategy: network-FIRST so a fresh build still wins on good signal, but
// fall back to cache after a short timeout so navigations stay fast on poor gym
// signal (and the cache keeps updating in the background — fresh next load).
function htmlStrategy(request) {
    return new Promise(resolve => {
        let settled = false;
        const finish = r => { if (!settled) { settled = true; resolve(r); } };
        // After 2.5s of waiting on the network, serve cache if we have it.
        const timer = setTimeout(() => {
            caches.match(request).then(cached => { if (cached) finish(cached); });
        }, 2500);
        fetch(request).then(resp => {
            if (resp && resp.status === 200) {
                const clone = resp.clone();
                caches.open(CACHE_NAME).then(c => c.put(request, clone));
            }
            clearTimeout(timer);
            finish(resp);   // no-op if the timeout already served cache; cache was still refreshed above
        }).catch(() => {
            clearTimeout(timer);
            caches.match(request).then(cached => finish(cached || offlinePage()));
        });
    });
}

// Fetch — HTML: network-first w/ fast cache fallback. CSS/JS/assets: network-first with cache fallback.
self.addEventListener('fetch', event => {
    const url = event.request.url;

    // Only handle requests to our domain
    if (!url.startsWith('https://mcross2298.github.io')) return;

    const isHTML = url.endsWith('.html') || url.endsWith('/') || !url.split('/').pop().includes('.');
    if (isHTML) {
        event.respondWith(htmlStrategy(event.request));
        return;
    }

    // CSS/JS/assets: network-first, cache fallback
    event.respondWith(
        fetch(event.request).then(resp => {
            if (resp && resp.status === 200) {
                const clone = resp.clone();
                caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
            }
            return resp;
        }).catch(() => {
            return caches.match(event.request).then(cached => {
                if (cached) return cached;
                return new Response(
                    '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">You are offline. Open this page while online to cache it.</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
                    {headers: {'Content-Type': 'text/html'}}
                );
            });
        })
    );
});

// Push — show notification from server-sent milestone alert
self.addEventListener('push', event => {
    let title = 'MC Training', body = 'You have a new milestone!', icon = './icon.svg';
    try {
        if (event.data) {
            const d = event.data.json();
            if (d.title) title = d.title;
            if (d.body)  body  = d.body;
            if (d.icon)  icon  = d.icon;
        }
    } catch (_) {}
    event.waitUntil(
        self.registration.showNotification(title, {
            body,
            icon,
            badge: './icon.svg',
            tag: 'mc-milestone',
            renotify: true
        })
    );
});

// Notification click — open the dashboard
self.addEventListener('notificationclick', event => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
            const dash = list.find(c => c.url.includes('dashboard.html'));
            if (dash) return dash.focus();
            return clients.openWindow('./dashboard.html');
        })
    );
});

// Message — force update
self.addEventListener('message', event => {
    if (event.data === 'skipWaiting') self.skipWaiting();
});