#!/usr/bin/env python3
"""
apply-head-contract.py — the canonical <head> every deployable page must carry.

Audit G-02/G-03 found that install metadata and theme bootstrapping were
hand-added per page, so coverage was whatever someone remembered: `viewport-fit`
and `apple-touch-icon` reached 145/145, but `rel="manifest"` stopped at 7 and
`theme-color` at 5. That meant the app was only installable from five of its
pages, and light-mode users saw a flash of dark theme on the other 132 because
the theme was applied by `mc-nav.js` from the END of <body>.

This tool owns a single block of head markup and writes it into every
deployable page — the same generate-and-verify pattern as build-sw.py and
check-script-manifest.py. No build step, no bundler: the markup is real and
greppable in every file, it is just not hand-maintained.

  python3 tools/apply-head-contract.py            # write the block into every page
  python3 tools/apply-head-contract.py --check    # CI: fail if any page drifted

Pages excluded: the design comps (*.dc.html) and stndr-card-concepts.html,
which pages.yml strips from the deploy artifact before publishing.
"""

import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Stripped from the Pages artifact by pages.yml, so they are never a real URL.
EXCLUDE = {'stndr-card-concepts.html'}

# Pure redirect stubs — they location.replace() on parse, so a service-worker
# update listener there would never live long enough to fire. They still get the
# head block (they are real install targets; index.html is the manifest's
# start_url), just not the tail module.
REDIRECT_STUBS = {'index.html', 'mc-home.html', 'pmc-home.html'}

# Loaded from the end of <body> on every non-stub page: surfaces the "new
# version available" path and guards against force-reloading mid-workout.
# Audit G-11 found it on 84 of 140 pages, so whether a user heard about a
# deploy depended on which page they happened to be sitting on.
TAIL_MODULE = 'mc-sw-update.js'
TAIL_TAG = '<script src="%s"></script>' % TAIL_MODULE
TAIL_RE = re.compile(r'<script[^>]*\bsrc="' + re.escape(TAIL_MODULE) + r'"[^>]*>\s*</script>', re.I)
BODY_CLOSE_RE = re.compile(r'</body>', re.I)


def excluded(name):
    return name.endswith('.dc.html') or name in EXCLUDE


START = '<!-- MC:HEAD START — generated by tools/apply-head-contract.py; edit there, not here -->'
END = '<!-- MC:HEAD END -->'

# Dark is the app default; light is the Sand ground from mc-light.css. Kept in
# sync with mc-theme.js's apply(), which re-resolves theme-color at runtime once
# an owner ThemeConfig is in play.
DARK_BG = '#0a0a0a'
LIGHT_BG = '#f5f2ec'

# Runs where it sits — after the theme-color tag it rewrites, before any body
# content paints. Inline on purpose: an external script in <head> would cost a
# blocking request on every page just to avoid a flash.
#
# Both behaviours previously lived at the END of <body> inside mc-nav.js, which
# is why a light-mode user saw a flash of dark on 132 pages and an installed-app
# cold launch rendered a whole deep page before bouncing to the dashboard.
# mc-nav.js no longer carries either one — this block is the only copy.
THEME_BOOT = (
    '<script>/* MC head boot (audit G-02/G-03) — PWA cold-launch guard + theme, before first paint */'
    'try{'
    # iOS captures the install-time URL and ignores the manifest start_url, so a
    # stale home-screen entry can open a deep page. Once per launch only, via a
    # session flag, so in-app navigation is never disturbed.
    'if((window.navigator.standalone===true||(window.matchMedia&&window.matchMedia'
    "('(display-mode: standalone)').matches))&&!sessionStorage.getItem('mc_launched')){"
    "sessionStorage.setItem('mc_launched','1');"
    "var _p=(location.pathname.split('/').pop()||'').toLowerCase();"
    "if(_p!==''&&_p!=='index.html'&&_p!=='dashboard.html'){location.replace('dashboard.html');}}"
    '}catch(e){}'
    'try{'
    "var _l=localStorage.getItem('mc_theme_mode')==='light';"
    "if(_l)document.documentElement.setAttribute('data-theme','light');"
    "var _m=document.querySelector('meta[name=\"theme-color\"]');"
    "if(_m)_m.setAttribute('content',_l?'" + LIGHT_BG + "':'" + DARK_BG + "');"
    '}catch(e){}</script>'
)

BLOCK = '\n'.join([
    START,
    '<link rel="manifest" href="manifest.json"/>',
    '<meta name="apple-mobile-web-app-capable" content="yes"/>',
    '<meta name="mobile-web-app-capable" content="yes"/>',
    '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>',
    '<meta name="apple-mobile-web-app-title" content="MC Training"/>',
    '<link rel="apple-touch-icon" href="apple-touch-icon.png"/>',
    '<meta name="theme-color" content="' + DARK_BG + '"/>',
    THEME_BOOT,
    END,
])

# Any pre-existing copy of a tag the block now owns, wherever it sits in <head>.
# The trailing match deliberately stops at ONE newline (`[ \t]*\r?\n?`) rather
# than using `\s*`: a greedy `\s*` also swallows the next line's indentation,
# which makes the tool non-idempotent — the second run re-indents whatever
# element followed a removed tag.
TAIL = r'[ \t]*\r?\n?'
MANAGED = [
    re.compile(r'[ \t]*<link[^>]*\brel="manifest"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-capable"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="mobile-web-app-capable"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-status-bar-style"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-title"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="theme-color"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<link[^>]*\brel="apple-touch-icon"[^>]*>' + TAIL, re.I),
    # The hand-rolled theme snippets this block replaces (audit G-03).
    re.compile(r'[ \t]*<script>\s*try\s*\{\s*if\s*\(\s*localStorage\.getItem\(\s*[\'"]mc_theme_mode[\'"]\s*\)'
               r'.*?</script>' + TAIL, re.I | re.S),
]

BLOCK_RE = re.compile(re.escape(START) + r'.*?' + re.escape(END) + TAIL, re.S)

VIEWPORT_RE = re.compile(r'<meta[^>]*\bname="viewport"[^>]*>', re.I)
TITLE_RE = re.compile(r'</title>', re.I)
HEAD_OPEN_RE = re.compile(r'<head[^>]*>', re.I)
HEAD_CLOSE_RE = re.compile(r'</head>', re.I)


def head_bounds(src):
    o = HEAD_OPEN_RE.search(src)
    c = HEAD_CLOSE_RE.search(src)
    if not o or not c or c.start() < o.end():
        return None
    return o.end(), c.start()


def build(src, name=''):
    """Return (new_src, problems). Idempotent."""
    problems = []
    b = head_bounds(src)
    if not b:
        return src, ['no parseable <head>']
    start, end = b
    head, rest_before, rest_after = src[start:end], src[:start], src[end:]

    # Contract requirements this tool verifies but never rewrites — they carry
    # page-specific content, so silently normalising them would be wrong.
    if not re.search(r'<html[^>]*\blang=', rest_before, re.I):
        problems.append('missing <html lang>')
    if not re.search(r'<meta[^>]*\bcharset=', head, re.I):
        problems.append('missing <meta charset>')
    vp = VIEWPORT_RE.search(head)
    if not vp:
        problems.append('missing viewport meta')
    elif 'viewport-fit=cover' not in vp.group(0):
        problems.append('viewport meta lacks viewport-fit=cover')

    # Strip a previous generated block, then any stray hand-added copies.
    head = BLOCK_RE.sub('', head)
    for rx in MANAGED:
        head = rx.sub('', head)

    # Anchor after </title> so the tab title stays the first meaningful thing in
    # the file; fall back to the viewport meta on the rare page with no <title>.
    m = TITLE_RE.search(head)
    if m:
        at = m.end()
    else:
        vp2 = VIEWPORT_RE.search(head)
        if not vp2:
            return src, problems + ['no <title> or viewport meta to anchor the block after']
        at = vp2.end()

    head = head[:at] + '\n' + BLOCK + head[at:]
    out = rest_before + head + rest_after

    # Tail contract: exactly one mc-sw-update.js, last in the body. Appending
    # rather than inserting mid-list keeps the check-script-manifest.py clone
    # families internally identical — every member of a family gains the tag at
    # the same position, so no family's ordered script list drifts from its
    # siblings.
    if name not in REDIRECT_STUBS and not TAIL_RE.search(out):
        m = BODY_CLOSE_RE.search(out)
        if not m:
            problems.append('no </body> to anchor %s' % TAIL_MODULE)
        else:
            out = out[:m.start()] + TAIL_TAG + '\n' + out[m.start():]
    return out, problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify only; exit 1 if any page would change')
    args = ap.parse_args()

    pages = sorted(p for p in glob.glob(os.path.join(ROOT, '*.html'))
                   if not excluded(os.path.basename(p)))

    drifted, broken, changed = [], [], []
    for path in pages:
        name = os.path.basename(path)
        with open(path, encoding='utf-8') as f:
            src = f.read()
        new, problems = build(src, name)
        if problems:
            broken.append((name, problems))
        if new != src:
            if args.check:
                drifted.append(name)
            else:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(new)
                changed.append(name)

    for name, problems in broken:
        for p in problems:
            print('::error file=%s::%s' % (name, p), file=sys.stderr)

    if args.check:
        for name in drifted:
            print('::error file=%s::head contract drifted — run '
                  'python3 tools/apply-head-contract.py' % name, file=sys.stderr)
        if drifted or broken:
            print('\n%d page(s) drifted, %d page(s) with contract violations.'
                  % (len(drifted), len(broken)), file=sys.stderr)
            return 1
        print('Head contract OK — %d pages carry the canonical block.' % len(pages))
        return 0

    if broken:
        print('\n%d page(s) have contract violations that must be fixed by hand.'
              % len(broken), file=sys.stderr)
    print('Head contract applied — %d pages checked, %d updated.'
          % (len(pages), len(changed)))
    return 1 if broken else 0


if __name__ == '__main__':
    sys.exit(main())
