#!/usr/bin/env python3
"""
apply-head-contract.py — the canonical <head> every deployable page must carry.

Audit G-02/G-03 found that install metadata and theme bootstrapping were
hand-added per page, so coverage was whatever someone remembered: `viewport-fit`
and `apple-touch-icon` reached 145/145, but `rel="manifest"` stopped at 7 and
`theme-color` at 5. That meant the app was only installable from five of its
pages, and light-mode users saw a flash of dark theme on the other 132 because
the theme was applied by `mc-nav.js` from the END of <body>.

This tool owns a single block of head markup and writes it into every
deployable page — the same generate-and-verify pattern as build-sw.py and
check-script-manifest.py. No build step, no bundler: the markup is real and
greppable in every file, it is just not hand-maintained.

  python3 tools/apply-head-contract.py            # write the block into every page
  python3 tools/apply-head-contract.py --check    # CI: fail if any page drifted

Pages excluded: the design comps (*.dc.html) and stndr-card-concepts.html,
which pages.yml strips from the deploy artifact before publishing.
"""

import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Stripped from the Pages artifact by pages.yml, so they are never a real URL.
EXCLUDE = {'stndr-card-concepts.html'}

# Pure redirect stubs — they location.replace() on parse, so a service-worker
# update listener there would never live long enough to fire. They still get the
# head block (they are real install targets; index.html is the manifest's
# start_url), just not the tail module.
REDIRECT_STUBS = {'index.html', 'mc-home.html', 'pmc-home.html'}

# Loaded from the end of <body> on every non-stub page: surfaces the "new
# version available" path and guards against force-reloading mid-workout.
# Audit G-11 found it on 84 of 140 pages, so whether a user heard about a
# deploy depended on which page they happened to be sitting on.
TAIL_MODULE = 'mc-sw-update.js'
TAIL_TAG = '<script src="%s"></script>' % TAIL_MODULE
TAIL_RE = re.compile(r'<script[^>]*\bsrc="' + re.escape(TAIL_MODULE) + r'"[^>]*>\s*</script>', re.I)
BODY_CLOSE_RE = re.compile(r'</body>', re.I)

# Sand light mode (audit G-04). Required on every page that loads base.css:
# mc-light.css covers the BESPOKE classes base.css's own
# html[data-theme="light"] block doesn't know about, so the two are a pair —
# a page with base.css but not this one renders half-themed in light mode.
# It was on 100 of 132 such pages, missing from the dashboard, the category
# landings, stats, and every split index and instructions guide.
#
# Position matters and is enforced, not just presence: it must be the LAST
# stylesheet in <head>, after base.css and after any inline <style>, because
# it wins by source order rather than specificity.
LIGHT_SHEET = 'mc-light.css'
LIGHT_TAG = '<link rel="stylesheet" href="%s">' % LIGHT_SHEET
LIGHT_RE = re.compile(r'[ \t]*<link[^>]*\bhref="' + re.escape(LIGHT_SHEET) + r'"[^>]*>' + r'[ \t]*\r?\n?', re.I)
BASE_RE = re.compile(r'<link[^>]*\bhref="base\.css', re.I)


def excluded(name):
    return name.endswith('.dc.html') or name in EXCLUDE


START = '<!-- MC:HEAD START — generated by tools/apply-head-contract.py; edit there, not here -->'
END = '<!-- MC:HEAD END -->'

# Dark is the app default; light is the Sand ground from mc-light.css. Kept in
# sync with mc-theme.js's apply(), which re-resolves theme-color at runtime once
# an owner ThemeConfig is in play.
DARK_BG = '#0a0a0a'
LIGHT_BG = '#f5f2ec'

# Runs where it sits — after the theme-color tag it rewrites, before any body
# content paints. Inline on purpose: an external script in <head> would cost a
# blocking request on every page just to avoid a flash.
#
# Both behaviours previously lived at the END of <body> inside mc-nav.js, which
# is why a light-mode user saw a flash of dark on 132 pages and an installed-app
# cold launch rendered a whole deep page before bouncing to the dashboard.
# mc-nav.js no longer carries either one — this block is the only copy.
THEME_BOOT = (
    '<script>/* MC head boot (audit G-02/G-03) — PWA cold-launch guard + theme, before first paint */'
    'try{'
    # iOS captures the install-time URL and ignores the manifest start_url, so a
    # stale home-screen entry can open a deep page. Once per launch only, via a
    # session flag, so in-app navigation is never disturbed.
    'if((window.navigator.standalone===true||(window.matchMedia&&window.matchMedia'
    "('(display-mode: standalone)').matches))&&!sessionStorage.getItem('mc_launched')){"
    "sessionStorage.setItem('mc_launched','1');"
    "var _p=(location.pathname.split('/').pop()||'').toLowerCase();"
    "if(_p!==''&&_p!=='index.html'&&_p!=='dashboard.html'){"
    # L7: iOS can silently kill a backgrounded installed PWA and hand the
    # relaunch a FRESH sessionStorage, so this guard's own launch flag reads
    # as unset — a trainee mid-set who only switched apps for a moment gets
    # bounced to the dashboard on return, losing their open card. mc_session_
    # v1 (mc-session.js) is the same store the dashboard's own resume banner
    # already reads for "you have an unfinished workout" — if it shows a
    # live record for THIS page (same 12h staleness window mc-session.js
    # itself prunes on, so this can't drift from that module's own
    # definition of "still current"), that's real in-progress work to
    # protect, so the redirect is skipped and the page opens where it is.
    "var _hasLive=false;"
    "try{"
    "var _sess=JSON.parse(localStorage.getItem('mc_session_v1')||'{}');"
    "var _rec=_sess[_p.replace('.html','')];"
    "_hasLive=!!(_rec&&(Date.now()-(_rec.lastTs||0))<43200000);"
    "}catch(e){}"
    "if(!_hasLive)location.replace('dashboard.html');"
    '}}'
    '}catch(e){}'
    'try{'
    # A page may opt out of light mode with <html data-theme-lock="dark">. Used
    # by the nine conditioning pages, whose conditioning-elite.css is an
    # explicitly dark "premium" design with no light grammar — letting the shell
    # go Sand while those cards stayed dark stranded white text on cream
    # (audit G-3.1). Locking here rather than fighting mc-light.css on
    # specificity means the light sheet simply never engages on them.
    "var _lk=document.documentElement.getAttribute('data-theme-lock');"
    "var _l=!_lk&&localStorage.getItem('mc_theme_mode')==='light';"
    "if(_l)document.documentElement.setAttribute('data-theme','light');"
    "var _m=document.querySelector('meta[name=\"theme-color\"]');"
    "if(_m)_m.setAttribute('content',_l?'" + LIGHT_BG + "':'" + DARK_BG + "');"
    '}catch(e){}'
    'try{'
    # S6: nothing in the app reported a runtime error anywhere outside a
    # CI/local console — a broken build was indistinguishable from a working
    # one until a user complained. A capped ring buffer (last 20), not a
    # third-party service: the goal is a breadcrumb trail an owner can pull
    # from the account sheet, not full telemetry. Registered here, in the
    # head block that runs before any other script on the page, specifically
    # so it catches an error thrown by one of THOSE other scripts too — a
    # listener added later (e.g. from mc-nav.js, loaded at the end of body
    # on most pages) would already have missed anything that happened
    # earlier in the page's own load.
    "var _erK='mc_errors_v1',_erMax=20;"
    "function _erRec(e){try{"
    "var a=JSON.parse(localStorage.getItem(_erK)||'[]');if(!Array.isArray(a))a=[];"
    "a.unshift(e);if(a.length>_erMax)a.length=_erMax;"
    "localStorage.setItem(_erK,JSON.stringify(a));"
    "}catch(_){}}"
    "window.addEventListener('error',function(ev){_erRec({t:Date.now(),k:'error',"
    "m:(ev&&ev.message)||'Unknown error',s:(ev&&ev.filename)||'',l:(ev&&ev.lineno)||0,"
    "p:(location.pathname.split('/').pop()||'')});});"
    "window.addEventListener('unhandledrejection',function(ev){var r=ev&&ev.reason;"
    "_erRec({t:Date.now(),k:'unhandledrejection',m:(r&&(r.message||String(r)))||'Unhandled rejection',"
    "p:(location.pathname.split('/').pop()||'')});});"
    '}catch(e){}</script>'
)

# DG-1/DG-2: the app's one type identity. Archivo (display) + Manrope (UI/body)
# were already the brand face on 9 of 13 cat-*.html landing pages and on
# dashboard.html — everywhere else silently rendered system-ui, since
# base.css's own font-family reset never had a webfont link to draw from
# (the "athletic" Bebas Neue PM theme option had the identical bug — see
# base.css's html[data-typography="athletic"] block, now retired). One
# canonical link, loaded and precached everywhere, rather than three
# competing (and in two cases entirely undelivered) identities.
FONT_HREF = ('https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;'
             '700;800;900&family=Manrope:wght@400;500;600;700;800&display=swap')
FONT_LINK = '<link href="%s" rel="stylesheet" media="print" onload="this.media=\'all\'"/>' % FONT_HREF
FONT_NOSCRIPT = '<noscript><link href="%s" rel="stylesheet"/></noscript>' % FONT_HREF
# U2: fonts.googleapis.com's own CSS response is what points the browser at
# fonts.gstatic.com in the first place, so on a cold load the actual font
# file's DNS+TLS handshake is only ever discovered AFTER that CSS parses —
# a fully serial round trip on a throttled connection. Preconnecting to the
# file host up front lets that handshake happen in parallel instead.
FONT_PRECONNECT = '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>'

BLOCK = '\n'.join([
    START,
    FONT_PRECONNECT,
    FONT_LINK,
    FONT_NOSCRIPT,
    '<link rel="manifest" href="manifest.json"/>',
    '<meta name="apple-mobile-web-app-capable" content="yes"/>',
    '<meta name="mobile-web-app-capable" content="yes"/>',
    '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>',
    '<meta name="apple-mobile-web-app-title" content="MC Training"/>',
    '<link rel="apple-touch-icon" href="apple-touch-icon.png"/>',
    '<meta name="theme-color" content="' + DARK_BG + '"/>',
    THEME_BOOT,
    END,
])

# Any pre-existing copy of a tag the block now owns, wherever it sits in <head>.
# The trailing match deliberately stops at ONE newline (`[ \t]*\r?\n?`) rather
# than using `\s*`: a greedy `\s*` also swallows the next line's indentation,
# which makes the tool non-idempotent — the second run re-indents whatever
# element followed a removed tag.
TAIL = r'[ \t]*\r?\n?'
MANAGED = [
    re.compile(r'[ \t]*<link[^>]*\brel="manifest"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-capable"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="mobile-web-app-capable"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-status-bar-style"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="apple-mobile-web-app-title"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<meta[^>]*\bname="theme-color"[^>]*>' + TAIL, re.I),
    re.compile(r'[ \t]*<link[^>]*\brel="apple-touch-icon"[^>]*>' + TAIL, re.I),
    # DG-1/DG-2: any pre-existing Google Fonts link — the 9 cat-*.html copies
    # of the same Archivo+Manrope pair this block now owns, and
    # cat-pump-new4.html's separate Bebas Neue+DM Sans pair being retired.
    # Broad host match on purpose so a stray future addition gets normalized
    # here too rather than becoming a second competing identity. The
    # <noscript>-wrapped copy MUST be matched (and stripped) before the bare
    # <link> pattern below — regex has no notion of HTML nesting, so if the
    # bare pattern ran first it would eat the <link> living INSIDE the
    # <noscript>, and the wrapper pattern would then find nothing left to
    # match, leaving a stray empty <noscript></noscript> behind.
    re.compile(r'[ \t]*<noscript>\s*<link[^>]*\bhref="https://fonts\.googleapis\.com/[^"]*"[^>]*>\s*</noscript>' + TAIL, re.I),
    re.compile(r'[ \t]*<link[^>]*\bhref="https://fonts\.googleapis\.com/[^"]*"[^>]*>' + TAIL, re.I),
    # U2: any pre-existing hand-rolled preconnect hint to either font host —
    # dashboard.html already carried its own pair before this block existed.
    # Normalized into the block so there's one copy, not two.
    re.compile(r'[ \t]*<link[^>]*\brel="preconnect"[^>]*\bhref="https://fonts\.(?:googleapis|gstatic)\.com[^"]*"[^>]*>' + TAIL, re.I),
    # The hand-rolled theme snippets this block replaces (audit G-03).
    re.compile(r'[ \t]*<script>\s*try\s*\{\s*if\s*\(\s*localStorage\.getItem\(\s*[\'"]mc_theme_mode[\'"]\s*\)'
               r'.*?</script>' + TAIL, re.I | re.S),
]

BLOCK_RE = re.compile(re.escape(START) + r'.*?' + re.escape(END) + TAIL, re.S)

VIEWPORT_RE = re.compile(r'<meta[^>]*\bname="viewport"[^>]*>', re.I)
TITLE_RE = re.compile(r'</title>', re.I)
HEAD_OPEN_RE = re.compile(r'<head[^>]*>', re.I)
HEAD_CLOSE_RE = re.compile(r'</head>', re.I)


def head_bounds(src):
    o = HEAD_OPEN_RE.search(src)
    c = HEAD_CLOSE_RE.search(src)
    if not o or not c or c.start() < o.end():
        return None
    return o.end(), c.start()


def build(src, name=''):
    """Return (new_src, problems). Idempotent."""
    problems = []
    b = head_bounds(src)
    if not b:
        return src, ['no parseable <head>']
    start, end = b
    head, rest_before, rest_after = src[start:end], src[:start], src[end:]

    # Contract requirements this tool verifies but never rewrites — they carry
    # page-specific content, so silently normalising them would be wrong.
    if not re.search(r'<html[^>]*\blang=', rest_before, re.I):
        problems.append('missing <html lang>')
    if not re.search(r'<meta[^>]*\bcharset=', head, re.I):
        problems.append('missing <meta charset>')
    vp = VIEWPORT_RE.search(head)
    if not vp:
        problems.append('missing viewport meta')
    elif 'viewport-fit=cover' not in vp.group(0):
        problems.append('viewport meta lacks viewport-fit=cover')

    # Strip a previous generated block, then any stray hand-added copies.
    head = BLOCK_RE.sub('', head)
    for rx in MANAGED:
        head = rx.sub('', head)

    # Anchor after </title> so the tab title stays the first meaningful thing in
    # the file; fall back to the viewport meta on the rare page with no <title>.
    m = TITLE_RE.search(head)
    if m:
        at = m.end()
    else:
        vp2 = VIEWPORT_RE.search(head)
        if not vp2:
            return src, problems + ['no <title> or viewport meta to anchor the block after']
        at = vp2.end()

    head = head[:at] + '\n' + BLOCK + head[at:]

    # Light-mode sheet: strip any existing copy, then re-add it last in <head>
    # so its position is normalised as well as its presence. Pages that don't
    # load base.css are left alone either way — three of them are fully
    # self-styled and opted in on their own, and adding it to the rest would
    # link a sheet whose selectors they never use.
    had_light = bool(LIGHT_RE.search(head))
    if had_light or BASE_RE.search(head):
        head = LIGHT_RE.sub('', head)
        head = head.rstrip() + '\n' + LIGHT_TAG + '\n'

    out = rest_before + head + rest_after

    # Tail contract: exactly one mc-sw-update.js, last in the body. Appending
    # rather than inserting mid-list keeps the check-script-manifest.py clone
    # families internally identical — every member of a family gains the tag at
    # the same position, so no family's ordered script list drifts from its
    # siblings.
    if name not in REDIRECT_STUBS and not TAIL_RE.search(out):
        m = BODY_CLOSE_RE.search(out)
        if not m:
            problems.append('no </body> to anchor %s' % TAIL_MODULE)
        else:
            out = out[:m.start()] + TAIL_TAG + '\n' + out[m.start():]
    return out, problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify only; exit 1 if any page would change')
    args = ap.parse_args()

    pages = sorted(p for p in glob.glob(os.path.join(ROOT, '*.html'))
                   if not excluded(os.path.basename(p)))

    drifted, broken, changed = [], [], []
    for path in pages:
        name = os.path.basename(path)
        with open(path, encoding='utf-8') as f:
            src = f.read()
        new, problems = build(src, name)
        if problems:
            broken.append((name, problems))
        if new != src:
            if args.check:
                drifted.append(name)
            else:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(new)
                changed.append(name)

    for name, problems in broken:
        for p in problems:
            print('::error file=%s::%s' % (name, p), file=sys.stderr)

    if args.check:
        for name in drifted:
            print('::error file=%s::head contract drifted — run '
                  'python3 tools/apply-head-contract.py' % name, file=sys.stderr)
        if drifted or broken:
            print('\n%d page(s) drifted, %d page(s) with contract violations.'
                  % (len(drifted), len(broken)), file=sys.stderr)
            return 1
        print('Head contract OK — %d pages carry the canonical block.' % len(pages))
        return 0

    if broken:
        print('\n%d page(s) have contract violations that must be fixed by hand.'
              % len(broken), file=sys.stderr)
    print('Head contract applied — %d pages checked, %d updated.'
          % (len(pages), len(changed)))
    return 1 if broken else 0


if __name__ == '__main__':
    sys.exit(main())
