#!/usr/bin/env python3
"""
sync-shared-modules.py — LS-1 of the Lean Six Sigma audit roadmap
(lean-six-sigma-audit.md, findings W-01/W-02/W-15). Successor to
sync-nutrition-modules.py, generalized to cover EVERY file the two apps share.

4-Weeks-to-Open- is the source of truth for all cross-app shared modules.
Two kinds of copies live in Mikes-Cookbook:

  GENERATED (banner prepended, renamed):
      mc-foodapi.js   -> tracker-foodapi.js
      mc-macrocalc.js -> tracker-calc.js
      mc-barcode.js   -> tracker-barcode.js

  BYTE-IDENTICAL (same name, no banner — the bridge contract depends on it):
      mc-bridge.js
      mc-install.js
      mc-backup-status.js
      tools/test-mc-bridge.js

Canonical files must stay app-agnostic: no hard dependency on a module only
one app loads (the mc-barcode.js MCInputSheet regression is the cautionary
tale — guard with a capability check and a fallback instead).

Local use (repos checked out as siblings; --cookbook-dir to override):
    python3 tools/sync-shared-modules.py            # write copies
    python3 tools/sync-shared-modules.py --check    # CI-style: fail if stale

CI use (either repo, no sibling checkout): download the counterpart's files
from raw.githubusercontent.com into a temp dir preserving relative paths,
then run --check with --root (canonical tree) and --cookbook-dir pointing at
whichever side is the download. See the "Shared-module drift check" step in
each repo's .github/workflows/pages.yml.

Landing order for a shared-module change: merge the 4-Weeks-to-Open- PR
first (canonical), then the Mikes-Cookbook PR (copies). The workout deploy
run between the two merges fails this check by design — re-run it after the
cookbook PR merges.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# canonical (workout repo) relative path -> cookbook relative path
GENERATED = {
    "mc-foodapi.js": "tracker-foodapi.js",
    "mc-macrocalc.js": "tracker-calc.js",
    "mc-barcode.js": "tracker-barcode.js",
}
IDENTICAL = [
    "mc-bridge.js",
    "mc-install.js",
    "mc-backup-status.js",
    "tools/test-mc-bridge.js",
]

BANNER_TMPL = (
    "/* AUTOGENERATED by tools/sync-shared-modules.py in 4-Weeks-to-Open- — "
    "do not hand-edit here.\n"
    "   Source: {src} in 4-Weeks-to-Open-. Fix upstream, then re-run the "
    "script to pick up the change. */\n"
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(ROOT),
                    help="canonical 4-Weeks-to-Open- tree (default: this repo)")
    ap.add_argument("--cookbook-dir", default=str(ROOT.parent / "Mikes-Cookbook"))
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any cookbook copy is stale, without writing")
    args = ap.parse_args()

    root = Path(args.root)
    cookbook_dir = Path(args.cookbook_dir)
    if not root.is_dir():
        sys.exit(f"canonical root not found: {root}")
    if not cookbook_dir.is_dir():
        sys.exit(f"cookbook dir not found: {cookbook_dir}")

    pairs = [(src, dst, BANNER_TMPL.format(src=src))
             for src, dst in GENERATED.items()]
    pairs += [(name, name, "") for name in IDENTICAL]

    stale = []
    for src_rel, dst_rel, banner in pairs:
        src_path = root / src_rel
        dst_path = cookbook_dir / dst_rel
        if not src_path.is_file():
            sys.exit(f"canonical file missing: {src_path}")
        wanted = banner + src_path.read_text(encoding="utf-8")

        if args.check:
            current = dst_path.read_text(encoding="utf-8") if dst_path.is_file() else ""
            if current != wanted:
                stale.append(dst_rel)
            continue

        dst_path.parent.mkdir(parents=True, exist_ok=True)
        dst_path.write_text(wanted, encoding="utf-8")
        print(f"synced {src_rel} -> {dst_rel}")

    if args.check:
        if stale:
            sys.exit("stale shared-module copies in Mikes-Cookbook (run "
                     "tools/sync-shared-modules.py in 4-Weeks-to-Open- to fix): "
                     + ", ".join(stale))
        print(f"shared modules in sync ({len(pairs)} files)")


if __name__ == "__main__":
    main()
