#!/usr/bin/env python3
"""
sync-nutrition-modules.py — Phase 1.1 of the nutrition-brain roadmap.

mc-foodapi.js, mc-macrocalc.js, and mc-barcode.js are the canonical copies of
the nutrition modules the workout app and Mike's Cookbook both need (Open
Food Facts search, the BMR/TDEE macro-goal calculator, and barcode scanning).
Historically each was hand-copied into the cookbook repo as tracker-*.js and
the two drifted apart in both directions (see the AUTOGEN banner below for
provenance). This script makes 4-Weeks-to-Open- the source of truth and
copies the canonical files into a sibling Mikes-Cookbook checkout under their
tracker-*.js names, unchanged apart from a generated-file banner.

Assumes both repos are checked out as siblings (../Mikes-Cookbook relative to
this repo's root) — pass --cookbook-dir to override.

Run from the repo root:
    python3 tools/sync-nutrition-modules.py            # sync
    python3 tools/sync-nutrition-modules.py --check     # CI-style: fail if stale
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# workout filename -> cookbook filename
MODULES = {
    "mc-foodapi.js": "tracker-foodapi.js",
    "mc-macrocalc.js": "tracker-calc.js",
    "mc-barcode.js": "tracker-barcode.js",
}

BANNER_TMPL = (
    "/* AUTOGENERATED by tools/sync-nutrition-modules.py in 4-Weeks-to-Open- — "
    "do not hand-edit here.\n"
    "   Source: {src} in 4-Weeks-to-Open-. Fix upstream, then re-run the "
    "script to pick up the change. */\n"
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cookbook-dir", default=str(ROOT.parent / "Mikes-Cookbook"))
    ap.add_argument("--check", action="store_true",
                     help="exit non-zero if any cookbook copy is stale, without writing")
    args = ap.parse_args()

    cookbook_dir = Path(args.cookbook_dir)
    if not cookbook_dir.is_dir():
        sys.exit(f"cookbook dir not found: {cookbook_dir}")

    stale = []
    for src_name, dst_name in MODULES.items():
        src_path = ROOT / src_name
        dst_path = cookbook_dir / dst_name
        source = src_path.read_text(encoding="utf-8")
        wanted = BANNER_TMPL.format(src=src_name) + source

        if args.check:
            current = dst_path.read_text(encoding="utf-8") if dst_path.exists() else ""
            if current != wanted:
                stale.append(dst_name)
            continue

        dst_path.write_text(wanted, encoding="utf-8")
        print(f"synced {src_name} -> {dst_path.relative_to(cookbook_dir.parent)}")

    if args.check:
        if stale:
            sys.exit("stale nutrition-module copies in cookbook (run without "
                      "--check to sync): " + ", ".join(stale))
        print("nutrition modules in sync")


if __name__ == "__main__":
    main()
